### PR TITLE
Add `http_proxy` parameter to Client

### PR DESCRIPTION
**Pull request by gcoxmoz**
## Description
Adds `http_proxy` support for hosts who need to go through a proxy to reach Duo servers.

## Motivation and Context
https://github.com/duosecurity/duo_universal_php/pull/5 is a PR that was accepted for "the same functionality" in "the same type of code" / a sibling project.

## How Has This Been Tested?
Tests added for args+kwargs passthrough.

## Types of Changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by AaronAtDuo** [comment]
@gcoxmoz the manual approval necessary to run CI timed out since it's been a month (sorry about that).  IIUC `git commit --amend` without making any actual changes should re-trigger the request for approval.

**Comment by gcoxmoz** [comment]
@AaronAtDuo Re-pushed; thanks for looking.

**Review by jeffreyparker — APPROVED** [review]

**Comment by AaronAtDuo** [comment]
@gcoxmoz Thanks for the PR!

**Comment by gcoxmoz** [comment]
NP.  Side note, it would be really great if this could get released+pypi'ed soonish.
Love and snuggles from universal-prompt-cutover-stragglers.

**Pull request merged**
